Repository tldraw/signia, pull requests merged in 2023-03, with the labels that each got.

#43 Fix react bindings doc links
  docs/docs/react-bindings.mdx
Labels: documentation

#44 Update intro.mdx
  docs/docs/intro.mdx
Labels: documentation

#45 [infra] fix docs ordering
  .github/workflows/enforce-label.yml
  docs/docs/react-bindings.mdx
  packages/signia/docs-ordering.json
  scripts/order-docs.ts
  scripts/prepare-docs.sh
Labels: documentation

#42 Create Github.png
  assets/Github.png
Labels: documentation

#46 remove -1 suffixes from docs titles
  scripts/order-docs.ts
Labels: documentation

#47 fix front matter again
  scripts/order-docs.ts
Labels: documentation

#48 [perf] improve ArraySet perf
  packages/signia/src/ArraySet.ts
Labels: patch, performance

#50 incremental docs fixes
  docs/docs/incremental.mdx
Labels: documentation

#52 [incremental docs] fix old descriptions
  docs/docs/what-are-signals.mdx
Labels: documentation

#55 fix signia-react-jsx build
  packages/signia-react-jsx/package.json
Labels: patch

#57 Update what-are-signals.mdx
  docs/docs/what-are-signals.mdx
Labels: documentation

#59 [fix] add getSeverSnapshot to support next et al
  packages/signia-react/src/useStateTracking.ts
  packages/signia-react/src/useValue.ts
Labels: patch

#60 make sure only one version of signia is loaded
  packages/signia/src/capture.ts
Labels: patch

#63 set auth token in canary script
  scripts/publish-canary.sh
Labels: internal

#64 [docs] fix typos in packages/signia
  packages/signia/src/Atom.ts
  packages/signia/src/Computed.ts
  packages/signia/src/helpers.ts
Labels: patch

#66 fix cjs/esm resolution
  jest-preset.js
  packages/signia-react-jsx/package.json
  packages/signia-react/src/index.ts
  packages/signia-react/src/track.test.tsx
  packages/signia-react/src/track.ts
  packages/signia-react/src/useAtom.test.tsx
  packages/signia-react/src/useComputed.test.tsx
  packages/signia-react/src/useStateTracking.test.tsx
  packages/signia-react/src/useValue.test.tsx
  packages/signia-react/src/wrapJsx.test.tsx
  packages/signia-react/src/wrapJsx.ts
  packages/signia/src/Atom.ts
  packages/signia/src/Computed.ts
  packages/signia/src/EffectScheduler.ts
  packages/signia/src/HistoryBuffer.ts
  packages/signia/src/__tests__/EffectScheduler.test.ts
  packages/signia/src/__tests__/HistoryBuffer.test.ts
  packages/signia/src/__tests__/arraySet.test.ts
  packages/signia/src/__tests__/atom.test.ts
  packages/signia/src/__tests__/capture.test.ts
  packages/signia/src/__tests__/computed.test.ts
  packages/signia/src/__tests__/fuzz.tlstate.test.ts
  packages/signia/src/__tests__/reactor.test.ts
  packages/signia/src/__tests__/transactions.test.ts
  packages/signia/src/api.ts
  packages/signia/src/capture.ts
  packages/signia/src/helpers.ts
  packages/signia/src/index.ts
  packages/signia/src/isSignal.ts
  packages/signia/src/transactions.ts
  packages/signia/src/types.ts
  scripts/build-package.ts
  scripts/prepack.ts
  tests/package-build/src/signia.test.ts
  tsconfig.base.json
Labels: minor

#68 [docs] fix discord links
  docs/docs/incremental.mdx
  docs/docusaurus.config.js
Labels: documentation
